### ISSUE TITLE
HTC 10 , Android 6.0.1

### ISSUE THREAD

**Issue by dimitrire** [ikarus23/MifareClassicTool#98] opened 2016-09-26 21:37 UTC
Hello,  mifare classic tool doesn't work on Android 6.0.1 , what do you think please ?

**Comment by dimitrire** [comment] 2016-09-26 23:45
the application says it is not a Mifare card while it worked fine on my htc one m7 with android 5.2

**Comment by ikarus23** [comment] 2016-09-27 05:32
This is odd again. There is a lot of strange behavior for HTC devices with Mifare Classic and Android 6+. (e.g. see https://github.com/ikarus23/MifareClassicTool/issues/89)

[This site](http://www.shopnfc.it/en/content/7-nfc-device-compatibility#htc) is claiming that the HTC 10 is not capable of reading/writing Mifare Classic tags. So MCT saying "this is not a Mifare Classic tag" might be a false positive...

Have you tried other NFC apps like [NFC TagInfo](https://play.google.com/store/apps/details?id=at.mroland.android.apps.nfctaginfo), [NFC TagInfo by NXP](https://play.google.com/store/apps/details?id=com.nxp.taginfolite) or [NFC Tools](https://play.google.com/store/apps/details?id=com.wakdev.wdnfc)?

**Comment by dimitrire** [comment] 2016-10-07 12:18
Hello I tested other applications but just detect the card, I made mistakes screens printed MCT, more when I read the map, areas that can only be read are random, that have never the same .

**Comment by dimitrire** [comment] 2016-10-07 12:23
![screenshot_20161007-140636](https://cloud.githubusercontent.com/assets/22459158/19189585/11e8d676-8c99-11e6-978f-23bbb61caec4.png)
![screenshot_20161007-140612](https://cloud.githubusercontent.com/assets/22459158/19189591/17ce35b8-8c99-11e6-9c78-2fecd3e2e1b4.png)
![screenshot_20161007-140546](https://cloud.githubusercontent.com/assets/22459158/19189596/1c479134-8c99-11e6-9a1d-960f9d154c9c.png)
![screenshot_20161007-140221](https://cloud.githubusercontent.com/assets/22459158/19189598/20f5dac4-8c99-11e6-8bf2-9b44a1706c3a.png)
![screenshot_20161007-142106](https://cloud.githubusercontent.com/assets/22459158/19189681/99de2130-8c99-11e6-9a94-7926a8c268bd.png)

**Comment by ikarus23** [comment] 2016-10-07 17:29
Ok, this is really strange. I never had a device that is working sometimes and sometimes not. Some of this issues might be caused by a bad antenna in the tag or the phone. but I'm not sure. Do you have other tags?

Have you ever read sector 0 successfully? On figure 3 it looks like this sector might be broken. Or this is some other false positive... And what is the content of the tag you are trying to write? Could you paste it here?

**Comment by dimitrire** [comment] 2016-10-07 22:52
Sector 0
74C21961CE880400C232000000000012
00000000000000000000000000000000
00000000000000000000000000000000
FFFFFFFFFFFFFF078069FFFFFFFFFFFF
Sector 1 to 7 and 15
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
FFFFFFFFFFFFFF078069FFFFFFFFFFFF
Sector8
20150C5E2876A56F8A35415003E10B07
1DC6A24E73A030CCD5B0479FC002883C
BE1270FBFB9952277A14F1BBFD5E4AD4
A0A1A2A3A4A50F00FFFF415A54454B4D
Sector9
6561AC1FC1A4E47B4959E7F1B0257470
CC8001659650A596BA87FF8F364B527D
C3BB2E514BC5311C9043BE710C549483
A0A1A2A3A4A50F00FFFF415A54454B4D
Sector10
BA87FF8F364B527D875EBCFDC50D3D28
4BCA79F4567E28A14959E7F1B0257470
BB0DDD075D499BE6BA87FF8F364B527D
A0A1A2A3A4A50F00FFFF415A54454B4D
Sector11
C3BB2E514BC5311C9043BE710C549483
BA87FF8F364B527D6867DE3057B907DB
D6A2FAA164E1B3B9BA87FF8F364B527D
A0A1A2A3A4A50F00FFFF415A54454B4D
Sector12.14
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
A0A1A2A3A4A50F00FFFF415A54454B4D
Sector13
D7FD3B612A8E04D2BA87FF8F364B527D
00000000000000000000000000000000
00000000000000000000000000000000
A0A1A2A3A4A50F00FFFF415A54454B4D

**Comment by dimitrire** [comment] 2016-10-07 22:54
The tag works on the machine

**Comment by dimitrire** [comment] 2016-10-07 22:57
The dump is to the HTC one m7

**Comment by dimitrire** [comment] 2016-10-25 18:45
The mifare was writed one shot of ten on the HTC 10

**Comment by ikarus23** [comment] 2017-01-08 21:51
It really looks like another Android 6+ NFC issue. Maybe this is not a fault of HTC. However, it is not an issue within MCT. Maybe it is related to [this Android bug](https://code.google.com/p/android/issues/detail?id=228344).

**Comment by ikarus23** [comment] 2017-10-30 13:27
Well, it really looks like exactly the same issue I'm having with my Google Nexus 5X. I'm closing this as it seams like it is a duplicate of https://github.com/ikarus23/MifareClassicTool/issues/106 and because it is most likely an Android issue...

**Closed by ikarus23** 2017-10-30 13:27 UTC
