### ISSUE TITLE
Dark Side attack on Mifare not working

### ISSUE THREAD

**Issue by niohundra** [ikarus23/MifareClassicTool#416] opened 2023-05-15 06:43 UTC
Hi, got a couple of questions on this, as i'm a beginner..

I bought a NFC reader, to copy access cards. One of these:
![image](https://github.com/ikarus23/MifareClassicTool/assets/133632531/28d8271b-1c78-4526-b34d-0c7c8b174892)

Long story short - I've got two identical cards, but they come with different access. Card 1 is an entry card, card 2 is entry + facilities. 
I've used the MifareTools Darkside Attack, set 6, attack sector 3-A. I've used the Windows build.

Card 1 is cracked within a minute, and i can save the entire dump. Card 2 seems impossible, it's been 52 hours for sector 3A, and nt diff and auth is just increasing. Around 1.1 million tries before i canceled it. 

What is my next step in this? Any suggestions?

**Comment by ikarus23** [comment] 2023-08-09 09:01
Hi. Sorry for the late response.
With that amount of information I don't know what the issue is. Do you know more about the second card? Is it a MIFARE Classic EV1 card? You should be able to check that with your Android phone and apps like NXP's TagInfo.
MFC EV1 (and some others) have an improved PRNG which makes the classic Darkside Attack impossible. As long as you know a single key (regardless which one) you better of with the Nested Attack. It is way faster. In case of MFC EV1 you can use the Hardnested Attack.

Hope this helps. I will close this issue, because is more of a question, not an issue. Feel free to document your progress here.

**Closed by ikarus23** 2023-08-09 09:01 UTC
Labels: question
